"""add user profile.

Revision ID: 8a36c8177c85
Revises: c7f2a08e4b1d
Create Date: 2026-08-30 10:42:06.148786

"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# Alembic 使用的迁移版本标识符。
revision: str = "8a36c8177c85"
down_revision: Union[str, Sequence[str], None] = "c7f2a08e4b1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("profile", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "profile")
    # ### end Alembic commands ###
